services:
  authserver:
    build: .
    container_name: lostandfound-authserver
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - APP_PROFILE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://lostandfound-postgres:5432/authdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - CORS_ORIGINS=http://localhost:5173,http://192.168.1.143:5173,https://app.sias.world,https://app.home03.eu
      - AUTH_ISSUER_URL=${AUTH_ISSUER_URL}
      - CLIENT_SECRET=${CLIENT_SECRET}
    networks:
      - lostandfound-network

networks:
  lostandfound-network:
    external: true
